"""add balance to wallet_top_up

Revision ID: 37d65ce64600
Revises: 013_add_item_indexes
Create Date: 2026-06-06 17:57:27.878476

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

revision: str = '37d65ce64600'
down_revision: Union[str, None] = '013_add_item_indexes'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('passwordreset',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_passwordreset_email'), 'passwordreset', ['email'], unique=False)
    op.create_index(op.f('ix_passwordreset_token'), 'passwordreset', ['token'], unique=True)
    op.create_index(op.f('ix_passwordreset_user_id'), 'passwordreset', ['user_id'], unique=False)
    op.drop_index(op.f('ix_otp_email'), table_name='otp')
    op.drop_table('otp')
    op.drop_index(op.f('ix_password_reset_email'), table_name='password_reset')
    op.drop_index(op.f('ix_password_reset_token'), table_name='password_reset')
    op.drop_index(op.f('ix_password_reset_user_id'), table_name='password_reset')
    op.drop_table('password_reset')
    op.alter_column('banner', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('banner', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('category', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('uq_chipset_key'), 'chipset', type_='unique')
    op.drop_index(op.f('ix_chipset_key'), table_name='chipset')
    op.create_index(op.f('ix_chipset_key'), 'chipset', ['key'], unique=True)
    op.drop_constraint(op.f('uq_device_brand_slug'), 'device_brand', type_='unique')
    op.drop_index(op.f('ix_device_brand_slug'), table_name='device_brand')
    op.create_index(op.f('ix_device_brand_slug'), 'device_brand', ['slug'], unique=True)
    op.drop_constraint(op.f('uq_tool_brand_chipset'), 'device_compatibility', type_='unique')
    op.create_index('uq_tool_brand_chipset', 'device_compatibility', ['tool_id', 'brand_slug', 'chipset_key'], unique=True)
    op.drop_constraint(op.f('device_compatibility_tool_id_fkey'), 'device_compatibility', type_='foreignkey')
    op.create_foreign_key(None, 'device_compatibility', 'device_tool', ['tool_id'], ['id'])
    op.drop_constraint(op.f('uq_device_tool_slug'), 'device_tool', type_='unique')
    op.drop_index(op.f('ix_device_tool_slug'), table_name='device_tool')
    op.create_index(op.f('ix_device_tool_slug'), 'device_tool', ['slug'], unique=True)
    op.drop_constraint(op.f('uq_issue_category_slug'), 'issue_category', type_='unique')
    op.drop_index(op.f('ix_issue_category_slug'), table_name='issue_category')
    op.create_index(op.f('ix_issue_category_slug'), 'issue_category', ['slug'], unique=True)
    op.alter_column('item', 'uid',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('item', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('item', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('order', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('order', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_promocodeusage_order_id'), table_name='promocodeusage')
    op.drop_index(op.f('ix_promocodeusage_promo_code_id'), table_name='promocodeusage')
    op.drop_index(op.f('ix_promocodeusage_user_id'), table_name='promocodeusage')
    op.alter_column('provider', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('technician', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_technician_user_id'), table_name='technician')
    op.create_unique_constraint(None, 'technician', ['user_id'])
    op.drop_constraint(op.f('uq_tool_issue'), 'tool_capability', type_='unique')
    op.create_index('uq_tool_issue', 'tool_capability', ['tool_id', 'issue_slug'], unique=True)
    op.drop_constraint(op.f('tool_capability_tool_id_fkey'), 'tool_capability', type_='foreignkey')
    op.create_foreign_key(None, 'tool_capability', 'device_tool', ['tool_id'], ['id'])
    op.alter_column('user', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.add_column('wallettopup', sa.Column('balance', sa.Numeric(precision=12, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wallettopup', 'balance')
    op.alter_column('user', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'tool_capability', type_='foreignkey')
    op.create_foreign_key(op.f('tool_capability_tool_id_fkey'), 'tool_capability', 'device_tool', ['tool_id'], ['id'], ondelete='CASCADE')
    op.drop_index('uq_tool_issue', table_name='tool_capability')
    op.create_unique_constraint(op.f('uq_tool_issue'), 'tool_capability', ['tool_id', 'issue_slug'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'technician', type_='unique')
    op.create_index(op.f('ix_technician_user_id'), 'technician', ['user_id'], unique=True)
    op.alter_column('technician', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('provider', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_promocodeusage_user_id'), 'promocodeusage', ['user_id'], unique=False)
    op.create_index(op.f('ix_promocodeusage_promo_code_id'), 'promocodeusage', ['promo_code_id'], unique=False)
    op.create_index(op.f('ix_promocodeusage_order_id'), 'promocodeusage', ['order_id'], unique=False)
    op.alter_column('order', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('order', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('item', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('item', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('item', 'uid',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_issue_category_slug'), table_name='issue_category')
    op.create_index(op.f('ix_issue_category_slug'), 'issue_category', ['slug'], unique=False)
    op.create_unique_constraint(op.f('uq_issue_category_slug'), 'issue_category', ['slug'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_device_tool_slug'), table_name='device_tool')
    op.create_index(op.f('ix_device_tool_slug'), 'device_tool', ['slug'], unique=False)
    op.create_unique_constraint(op.f('uq_device_tool_slug'), 'device_tool', ['slug'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'device_compatibility', type_='foreignkey')
    op.create_foreign_key(op.f('device_compatibility_tool_id_fkey'), 'device_compatibility', 'device_tool', ['tool_id'], ['id'], ondelete='CASCADE')
    op.drop_index('uq_tool_brand_chipset', table_name='device_compatibility')
    op.create_unique_constraint(op.f('uq_tool_brand_chipset'), 'device_compatibility', ['tool_id', 'brand_slug', 'chipset_key'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_device_brand_slug'), table_name='device_brand')
    op.create_index(op.f('ix_device_brand_slug'), 'device_brand', ['slug'], unique=False)
    op.create_unique_constraint(op.f('uq_device_brand_slug'), 'device_brand', ['slug'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_chipset_key'), table_name='chipset')
    op.create_index(op.f('ix_chipset_key'), 'chipset', ['key'], unique=False)
    op.create_unique_constraint(op.f('uq_chipset_key'), 'chipset', ['key'], postgresql_nulls_not_distinct=False)
    op.alter_column('category', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('banner', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('banner', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_table('password_reset',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_used', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('password_reset_pkey'))
    )
    op.create_index(op.f('ix_password_reset_user_id'), 'password_reset', ['user_id'], unique=False)
    op.create_index(op.f('ix_password_reset_token'), 'password_reset', ['token'], unique=True)
    op.create_index(op.f('ix_password_reset_email'), 'password_reset', ['email'], unique=False)
    op.create_table('otp',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('code_hash', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('purpose', sa.VARCHAR(), server_default=sa.text("'REGISTER'::character varying"), autoincrement=False, nullable=False),
    sa.Column('is_used', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('otp_pkey'))
    )
    op.create_index(op.f('ix_otp_email'), 'otp', ['email'], unique=False)
    op.drop_index(op.f('ix_passwordreset_user_id'), table_name='passwordreset')
    op.drop_index(op.f('ix_passwordreset_token'), table_name='passwordreset')
    op.drop_index(op.f('ix_passwordreset_email'), table_name='passwordreset')
    op.drop_table('passwordreset')
    # ### end Alembic commands ###